baseURL = 'https://skjermfribarndom-no.github.io//'
languageCode = 'no'
title = 'Skjermfri barndom'
theme = 'ananke'
defaultContentLanguage = 'no'

[params]
  description = "Skjermfri barndom"
  custom_css = ["site.css"]
