baseURL = 'https://skjermfribarndom.no'
languageCode = 'no'
title = 'Skjermfri barndom'
theme = 'ananke'
defaultContentLanguage = 'no'

[params]
  description = "Skjermfri barndom"
  custom_css = ["site.css"]

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/venttil13"

